[[edge_functions]]
    function = "hello"
    path = "/*"
    excludedPath = [
    "/*.css",
    "/*.js",
    "/*json",
    "/*.png",
    "/*.jpg",
    "/*.webp",
    "/*.svg",
    "/static/*",
    "/manifest.webmanifest",
    ]

    [edge_functions.header]
    x-no-edge = false


[context.dev]
  [[edge_functions]]
  function = "hello"
  path     = "/__noop_dev_route__/*"



[[headers]]
  for = "/*"
  [headers.values]
    x-no-edge = "yes"