name: Relyance SCI Scan


on:
 schedule:
   - cron: "0 5 * * 0"
 workflow_dispatch:


jobs:
 execute-relyance-sci:
   name: Relyance SCI Job
   runs-on: ubuntu-latest
   env:
     API_KEY: ${{ secrets.RELYANCE_API_KEY }}


   steps:
     - name: Checkout
       uses: actions/checkout@v4


     - name: Pull and run SCI binary
       run: |-
         docker pull gcr.io/relyance-ext/compliance_inspector:release &&          docker run --rm -v `pwd`:/repo --env "API_KEY=$API_KEY"          gcr.io/relyance-ext/compliance_inspector:release
